### ISSUE TITLE
Returned value should be unknown type

### ISSUE THREAD

**Issue by chrbala** [astoilkov/use-local-storage-state#32]
The `value` in `[value, setValue] = useLocalStorageState('key')` can be updated outside of the closure: dev tools, different app versions, different parts of the app with the same key, etc. To avoid runtime errors, `value` should therefore be typed as `unknown` so that assertions (or coercions) are explicitly made before treating the output type the same as the input type.

**Comment by astoilkov** [comment]
I agree. I've made the change. Thanks for the idea!

**Comment by chrbala** [comment]
It looks like [the change](https://github.com/astoilkov/use-local-storage-state/commit/2f8c0e8c1693db8952f3b9f3a7a1d6e80b6e9612) typed it as `[unknown, UpdateState<unknown>]`, but actually it's valid to type it as `[unknown, UpdateState<T>]`. That will _enforce_ the types going in to the state, but will not _guarantee_ the types coming out.

**Comment by astoilkov** [comment]
Hmm. But you don't know the types going into the state. My understanding is that there isn't a practical difference between `UpdateState<unknown>` and `UpdateState<T>` because of the other overrides that capture the other cases where we know the type. Am I wrong? Can you show an example where there is a difference?

**Comment by chrbala** [comment]
Ah, looks like you're right, I missed that. Thanks!
