### ISSUE TITLE
I have a problem using the use-local-storage-state

### ISSUE THREAD

**Issue by marcosvspimenta** [astoilkov/use-local-storage-state#48]
I have this problem here.  https://stackoverflow.com/questions/71759515/icons-are-not-showing-after-clicking-close

I think it's because of use-local-storage-state

Can anybody help me?

**Comment by astoilkov** [comment]
Can you try to upgrade to version 17.0.1 (I just published it) and see if the issue still persists?

**Comment by astoilkov** [comment]
I've tried running the CodeSandbox example you provided in the StackOverflow question but the demo is throwing a lot of errors. See below:
<img width="889" alt="CleanShot 2022-04-07 at 12 23 56@2x" src="https://user-images.githubusercontent.com/884810/162167114-0e54d203-360a-40c0-9d19-9893714677f6.png">

Also I tried forking the example and running it and this caused other errors. See below:
<img width="516" alt="CleanShot 2022-04-07 at 12 25 59@2x" src="https://user-images.githubusercontent.com/884810/162167531-55461d07-0ead-4417-906f-050898c2337a.png">

I'm not sure I can help you as this will require a huge amount of time and effort in order to fix all the errors and understand what's happening. Can you fix the errors? I can then debug what's happening in `use-local-storage-state` hook from there.

**Comment by marcosvspimenta** [comment]
I don't know what happened but now it's gone in https://codesandbox.io/embed/determined-monad-v4cp38?fontsize=14&hidenavigation=1&theme=dark

and the error can be reproduced

**Comment by marcosvspimenta** [comment]
I see it now, I'll see what I can do to fix it.

**Comment by astoilkov** [comment]
@marcosvspimenta Did you find out the problem?

**Comment by astoilkov** [comment]
I'm closing this because there is a lack of activity. I will reopen if there is a new comment.
